/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./src/**/*.{html,js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eef0ff",
        "surface-container-high": "#e2e7ff",
        "on-primary-container": "#bec8ff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#dae2fd",
        "tertiary-fixed": "#c9e6ff",
        "surface-dim": "#d2d9f4",
        "on-primary": "#ffffff",
        "tertiary-container": "#005b83",
        "surface-tint": "#294fdb",
        outline: "#747686",
        "inverse-primary": "#b8c3ff",
        "on-surface": "#131b2e",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed": "#0b1c30",
        surface: "#faf8ff",
        secondary: "#505f76",
        background: "#faf8ff",
        "on-tertiary-container": "#93d2ff",
        "surface-container": "#eaedff",
        "outline-variant": "#c4c5d7",
        primary: "#1A45D2",
        accent: "#FD644C",
        "on-secondary-container": "#54647a",
        "surface-container-low": "#f2f3ff",
        "on-tertiary-fixed": "#001e2f",
        "primary-container": "#1a45d2",
        "accent-container": "#FD644C",
        error: "#ba1a1a",
        "inverse-surface": "#283044",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#38485d",
        "secondary-container": "#d0e1fb",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b7c8e1",
        "tertiary-fixed-dim": "#89ceff",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#444655",
        "primary-fixed": "#dde1ff",
        "on-primary-fixed-variant": "#0035bd",
        "on-primary-fixed": "#001355",
        "surface-variant": "#dae2fd",
        "secondary-fixed": "#d3e4fe",
        "on-background": "#131b2e",
        "primary-fixed-dim": "#b8c3ff",
        tertiary: "#004261",
        "on-tertiary-fixed-variant": "#004c6e",
        "node-green": "#2e7d32",
        "node-purple": "#7b1fa2",
        "node-amber": "#f9a825",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        gutter: "24px",
        "grid-unit": "8px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      fontFamily: {
        headline: ["Geist"],
        label: ["JetBrains Mono"],
        body: ["Geist"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-xl": ["180px", { lineHeight: "1", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
