// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type ContactSubmission struct {
	ID                 int64  `json:"id"`
	FullName           string `json:"full_name"`
	CorporateEmail     string `json:"corporate_email"`
	WorkflowBottleneck string `json:"workflow_bottleneck"`
	CreatedAt          string `json:"created_at"`
}

type PartnerContactSubmission struct {
	ID                 int64  `json:"id"`
	AgencyName         string `json:"agency_name"`
	CorporateEmail     string `json:"corporate_email"`
	ClientVolume       string `json:"client_volume"`
	PrimaryVertical    string `json:"primary_vertical"`
	DeliveryConstraint string `json:"delivery_constraint"`
	CreatedAt          string `json:"created_at"`
}
