// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
)

const createContactSubmission = `-- name: CreateContactSubmission :one
INSERT INTO contact_submissions (
    full_name,
    corporate_email,
    workflow_bottleneck
) VALUES (?, ?, ?)
RETURNING id, full_name, corporate_email, workflow_bottleneck, created_at
`

type CreateContactSubmissionParams struct {
	FullName           string `json:"full_name"`
	CorporateEmail     string `json:"corporate_email"`
	WorkflowBottleneck string `json:"workflow_bottleneck"`
}

func (q *Queries) CreateContactSubmission(ctx context.Context, arg CreateContactSubmissionParams) (ContactSubmission, error) {
	row := q.db.QueryRowContext(ctx, createContactSubmission, arg.FullName, arg.CorporateEmail, arg.WorkflowBottleneck)
	var i ContactSubmission
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.CorporateEmail,
		&i.WorkflowBottleneck,
		&i.CreatedAt,
	)
	return i, err
}

const createPartnerContactSubmission = `-- name: CreatePartnerContactSubmission :one
INSERT INTO partner_contact_submissions (
    agency_name,
    corporate_email,
    client_volume,
    primary_vertical,
    delivery_constraint
) VALUES (?, ?, ?, ?, ?)
RETURNING id, agency_name, corporate_email, client_volume, primary_vertical, delivery_constraint, created_at
`

type CreatePartnerContactSubmissionParams struct {
	AgencyName         string `json:"agency_name"`
	CorporateEmail     string `json:"corporate_email"`
	ClientVolume       string `json:"client_volume"`
	PrimaryVertical    string `json:"primary_vertical"`
	DeliveryConstraint string `json:"delivery_constraint"`
}

func (q *Queries) CreatePartnerContactSubmission(ctx context.Context, arg CreatePartnerContactSubmissionParams) (PartnerContactSubmission, error) {
	row := q.db.QueryRowContext(ctx, createPartnerContactSubmission,
		arg.AgencyName,
		arg.CorporateEmail,
		arg.ClientVolume,
		arg.PrimaryVertical,
		arg.DeliveryConstraint,
	)
	var i PartnerContactSubmission
	err := row.Scan(
		&i.ID,
		&i.AgencyName,
		&i.CorporateEmail,
		&i.ClientVolume,
		&i.PrimaryVertical,
		&i.DeliveryConstraint,
		&i.CreatedAt,
	)
	return i, err
}
